"""empty message

Revision ID: b30d2acbb6a7
Revises: f2a0ac03e4df
Create Date: 2025-09-18 15:29:20.251841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b30d2acbb6a7'
down_revision: Union[str, Sequence[str], None] = 'f2a0ac03e4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_Id'), table_name='trades')
    op.drop_index(op.f('ix_trades_Ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_Timestamp'), table_name='trades')
    op.drop_table('trades')
    op.add_column('indicators', sa.Column('Timeframe', sa.String(), nullable=False))
    op.create_index(op.f('ix_indicators_Timeframe'), 'indicators', ['Timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_Timeframe'), table_name='indicators')
    op.drop_column('indicators', 'Timeframe')
    op.create_table('trades',
    sa.Column('Id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('Price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('Quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('Side', postgresql.ENUM('Buy', 'Sell', name='tradeside'), autoincrement=False, nullable=False),
    sa.Column('IsMaker', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name=op.f('trades_pkey'))
    )
    op.create_index(op.f('ix_trades_Timestamp'), 'trades', ['Timestamp'], unique=False)
    op.create_index(op.f('ix_trades_Ticker'), 'trades', ['Ticker'], unique=False)
    op.create_index(op.f('ix_trades_Id'), 'trades', ['Id'], unique=False)
    # ### end Alembic commands ###
