"""empty message

Revision ID: f2a0ac03e4df
Revises: 
Create Date: 2025-09-14 12:04:59.316733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a0ac03e4df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Timeframe', sa.String(), nullable=False),
    sa.Column('Timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('Open', sa.Float(), nullable=False),
    sa.Column('High', sa.Float(), nullable=False),
    sa.Column('Low', sa.Float(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=False),
    sa.Column('Volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_candles_Id'), 'candles', ['Id'], unique=False)
    op.create_index(op.f('ix_candles_Ticker'), 'candles', ['Ticker'], unique=False)
    op.create_index(op.f('ix_candles_Timeframe'), 'candles', ['Timeframe'], unique=False)
    op.create_index(op.f('ix_candles_Timestamp'), 'candles', ['Timestamp'], unique=False)
    op.create_table('levels',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('LevelPrice', sa.Float(), nullable=False),
    sa.Column('Strength', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Enum('Support', 'Resistance', name='leveltype'), nullable=False),
    sa.Column('LastTouched', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_levels_Id'), 'levels', ['Id'], unique=False)
    op.create_index(op.f('ix_levels_Ticker'), 'levels', ['Ticker'], unique=False)
    op.create_table('order_book',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('Bids', sa.JSON(), nullable=False),
    sa.Column('Asks', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_order_book_Id'), 'order_book', ['Id'], unique=False)
    op.create_index(op.f('ix_order_book_Ticker'), 'order_book', ['Ticker'], unique=False)
    op.create_table('trades',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Quantity', sa.Float(), nullable=False),
    sa.Column('Side', sa.Enum('Buy', 'Sell', name='tradeside'), nullable=False),
    sa.Column('IsMaker', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_trades_Id'), 'trades', ['Id'], unique=False)
    op.create_index(op.f('ix_trades_Ticker'), 'trades', ['Ticker'], unique=False)
    op.create_index(op.f('ix_trades_Timestamp'), 'trades', ['Timestamp'], unique=False)
    op.create_table('indicators',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CandleId', sa.Integer(), nullable=False),
    sa.Column('Ema9', sa.Float(), nullable=True),
    sa.Column('Ema21', sa.Float(), nullable=True),
    sa.Column('Rsi', sa.Float(), nullable=True),
    sa.Column('Macd', sa.Float(), nullable=True),
    sa.Column('MacdSignal', sa.Float(), nullable=True),
    sa.Column('MacdHist', sa.Float(), nullable=True),
    sa.Column('BbHigh', sa.Float(), nullable=True),
    sa.Column('BbLow', sa.Float(), nullable=True),
    sa.Column('BbMid', sa.Float(), nullable=True),
    sa.Column('Atr', sa.Float(), nullable=True),
    sa.Column('Obv', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['CandleId'], ['candles.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_indicators_Id'), 'indicators', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_Id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_trades_Timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_Ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_Id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_order_book_Ticker'), table_name='order_book')
    op.drop_index(op.f('ix_order_book_Id'), table_name='order_book')
    op.drop_table('order_book')
    op.drop_index(op.f('ix_levels_Ticker'), table_name='levels')
    op.drop_index(op.f('ix_levels_Id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_candles_Timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_Timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_Ticker'), table_name='candles')
    op.drop_index(op.f('ix_candles_Id'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
